### ISSUE TITLE
`index out of bounds` error in `allel_frequencies` vector in `oncoprint.rs`

### ISSUE THREAD

**Issue by dlaehnemann** [rust-bio/rust-bio-tools#77]
Running the following command goes well for quite a while (minutes to hours), but finally I get a panic:
```
RUST_BACKTRACE=full rbt vcf-report   resources/genome.fasta   --bams 18:18_B=results/mapped/18_B.sorted.bam 18:18_C=results/mapped/18_C.sorted.bam 18:18_D=results/mapped/18_D.sorted.bam 18:18_F=results/mapped18_F.sorted.bam   --vcfs 18=results/annotated-calls/18.basic.present.1.fdr-controlled.two_samples_cov.annotated.bcf   -f DP AF OBS   -i  PROB_PRESENT PROB_ARTIFACT PROB_ABSENT   -j workflow/resources/custom-table-report.js   -- results/vcf-report/18.basic.present.1.fdr-controlled.annotated/
```

It seems to come from this code line:
https://github.com/rust-bio/rust-bio-tools/blob/387429777db8d062d43d731352ec4d55a7c91015/src/bcf/report/oncoprint.rs#L181

And here's the full backtrace, although I think the most useful info is the first row at the top, with the line number included:
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/bcf/report/oncoprint.rs:181:50
stack backtrace:
   0:     0x556dbf4f99f0 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x556dbf4f99f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x556dbf4f99f0 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:     0x556dbf4f99f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:     0x556dbf52197c - core::fmt::write::h9ddafa4860d8adff
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:     0x556dbf4f3a77 - std::io::Write::write_fmt::h1d2ee292d2b65481
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:     0x556dbf4fc250 - std::sys_common::backtrace::_print::ha25f9ff5080d886d  
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   7:     0x556dbf4fc250 - std::sys_common::backtrace::print::h213e8aa8dc5405c0   
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   8:     0x556dbf4fc250 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
   9:     0x556dbf4fbf9c - std::panicking::default_hook::he30ad7589e0970f9
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
  10:     0x556dbf4fc8b3 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
  11:     0x556dbf4fc489 - std::panicking::begin_panic_handler::{{closure}}::h7001af1bb21aeaeb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
  12:     0x556dbf4f9e7c - std::sys_common::backtrace::__rust_end_short_backtrace::h39910f557f5f2367
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
  13:     0x556dbf4fc449 - rust_begin_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
  14:     0x556dbf51f541 - core::panicking::panic_fmt::h4e2659771ebc78eb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
  15:     0x556dbf51f502 - core::panicking::panic_bounds_check::h2e8c50d2fb4877c0 
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:62
  16:     0x556dbebd8d03 - rbt::bcf::report::oncoprint::oncoprint::h30b8a45d1d21b2d7
  17:     0x556dbeb6db17 - rbt::main::h284af7b901acdb78
  18:     0x556dbebc1e23 - std::sys_common::backtrace::__rust_begin_short_backtrace::h75709365801ea186
  19:     0x556dbeb293ed - std::rt::lang_start::{{closure}}::hcf4c7d8d71619a23
  20:     0x556dbf4fcd81 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6a3209f124be2235
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259
  21:     0x556dbf4fcd81 - std::panicking::try::do_call::h88ce358792b64df0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
  22:     0x556dbf4fcd81 - std::panicking::try::h6311c259678e50fc
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
  23:     0x556dbf4fcd81 - std::panic::catch_unwind::h56c5716807d659a1
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
  24:     0x556dbf4fcd81 - std::rt::lang_start_internal::h73711f37ecfcb277
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51
  25:     0x556dbeb6fc62 - main
  26:     0x7fb9c0181b97 - __libc_start_main
  27:     0x556dbeaf4651 - <unknown>
```

@fxwiegand: Am I specifying the samples for this group wrong somehow? Or is this a bug? It seems like the vector `allel_frequencies` from before does not have an entry for every sample at some point:
https://github.com/rust-bio/rust-bio-tools/blob/387429777db8d062d43d731352ec4d55a7c91015/src/bcf/report/oncoprint.rs#L77

But I double-checked the input BCF file with:
```
bcftools query -f '%CHROM\t%POS\t%ALT[\t%SAMPLE=%AF]\n' 18.basic.present.1.fdr-controlled.two_samples_cov.annotated.bcf | less
```
And this gives an `AF` FORMAT field entry for every sample at every given genomic position. So I'm not sure what might be triggering this behaviour. If you have any further ideas, I'd be glad to investigate further.

**Comment by fxwiegand** [comment]
@dlaehnemann You are absolutely right. The problem was the following line (and of course it's later usage): https://github.com/rust-bio/rust-bio-tools/blob/387429777db8d062d43d731352ec4d55a7c91015/src/bcf/report/oncoprint.rs#L77

It was still part of code that assumed that the input VCFs were only single-sample files. In fact I should have updated the handling of the format data with https://github.com/rust-bio/rust-bio-tools/pull/67 but just overlooked that. 

https://github.com/rust-bio/rust-bio-tools/pull/78 should fix the problem.
